### ISSUE TITLE
MultiSample VCF

### ISSUE THREAD

**Issue by snashraf** [cc2qe/vawk#12]
Hi.

How does it work on multisample VCF ? I wanted to filter multisample VCF file based genotype from 2 individuals . 
I am using this command .
zcat PMC01.vcf.gz | vawk --header 'S$AB082422_S5_L005$GT=="0/0"' && 'S$ABC09005_S2_L002$GT=="0/1"

This is not filtering properly. 
Can you please help me on this ?

**Comment by cc2qe** [comment]
try this:
```
zcat PMC01.vcf.gz | vawk --header 'S$AB082422_S5_L005$GT=="0/0" && S$ABC09005_S2_L002$GT=="0/1"'
```

**Comment by snashraf** [comment]
Thanks !!

On Tue, May 31, 2016 at 1:37 PM, Colby Chiang <notifications@github.com>
wrote:

> try this:
>
> zcat PMC01.vcf.gz | vawk --header 'S$AB082422_S5_L005$GT=="0/0" && S$ABC09005_S2_L002$GT=="0/1"'
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cc2qe/vawk/issues/12#issuecomment-222652544>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEJUN346HjQroCAJWhXPWKHlE1-3OrsXks5qHA9kgaJpZM4IqNfK>
> .
>



-- 
Syed Najeeb Ashraf
